version: 2

sources:
  - name: raw
    description: "Raw data from Alteryx processing, loaded into Snowflake"
    schema: RAWDATA
    database: SUPPLYCHAINDB
    tables:
      - name: dataCoSupplyChainOrders
        description: "Raw supply chain orders with Alteryx-enriched fields (camelCase columns)"
      - name: clickstreamEvents
        description: "Raw clickstream events with Alteryx-enriched fields (camelCase columns)"

