name: 'dbtTransformations'
version: '1.0.0'
config-version: 2

profile: 'supply_chain'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbtTransformations:
    staging:
      +schema: analyticalData
      +materialized: view
    marts:
      dimensions:
        +schema: analyticalData
        +materialized: table
      facts:
        +schema: analyticalData
        +materialized: table
      analytics:
        +schema: martData
        +materialized: table
